name: devops
on: [push]
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make test.sh executable
        run: chmod +x test.sh
      - name: Run test.sh
        run: ./test.sh
